language: ruby

sudo: false

before_install: gem install bundler

rvm:
  - 2.2

script: bundle exec rspec spec
 - travis-lint

matrix:
  # fast_finish will prevent allowed failed process from delaying build
  fast_finish: true
