language: ruby

before_install: gem install bundler

rvm:
  - 2.2
env:
#  - DB=sqlite
#  - DB=mysql
  - DB=postgresql

before_script:
  - psql -c 'create database zipshare-api_test' -U postgres

script: bundle exec rspec spec


matrix:
  # fast_finish will prevent allowed failed process from delaying build
  fast_finish: true
